services:
  mysql:
    image: mysql:8.0
    container_name: hireflow-mysql
    restart: always

    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mydata:/var/lib/mysql

volumes:
  mydata: